<?xml version="1.0"?>
<package format="3">
  <name>arena_tracker_pkg</name>
  <version>0.0.1</version>
  <description>C++ ROS 2 Node for Arena Tracking</description>
  <maintainer email="vlad@todo.todo">Vlad</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>opencv</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
